debug changes3

diff --git a/.github/workflows/ci-locks.yml b/.github/workflows/ci-locks.yml
--- a/.github/workflows/ci-locks.yml
+++ b/.github/workflows/ci-locks.yml
@@ -89,15 +89,24 @@ jobs:
         path: ${{ github.workspace }}/.tox
         key: ${{ runner.os }}-tox-${{ env.ENV_NAME }}-${{ matrix.lock }}-p${{ env.CACHE_PERIOD }}-b${{ env.CACHE_BUILD }}-${{ hashFiles(env.TOX_INI) }}
 
-    - name: "Create ${{ matrix.lock }} conda locks"
-      run: |
-        tox -e ${{ matrix.lock }} -- --platform osx-64 --platform win-64
-
-    - name: "Confirm working dir"
+    - name: "Confirm working dir (1)"
       run: |
         pwd
 
-    - name: "Check for local changes"
+    - name: "Check for local changes (1)"
+      run: |
+        git status
+
+    - name: "Create ${{ matrix.lock }} conda locks"
+      run: |
+        # Omitted temporarily : -- --platform osx-64 --platform win-64
+        tox -e ${{ matrix.lock }} || echo "(FAILED)."
+
+    - name: "Confirm working dir (2)"
+      run: |
+        pwd
+
+    - name: "Check for local changes (2)"
       run: |
         git status
 
